name: build

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Execute Tests
      run: make tests
    - name: Update Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage/coverage.out -service=github
