name: docker
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (main)
        id: docker_build
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: madflojo/tarmac:unstable
      - name: Checkout code and fetch all tags
        run: |
          git fetch --tags
          echo "current_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
          echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: Build and push (tag)
        id: docker_build_tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          # tag with the git tag v*
          tags: |
            madflojo/tarmac:${{ github.ref_name }}
            ${{ env.latest_tag == env.current_tag && 'madflojo/tarmac:latest' }}
